- hosts: "{{ target | default('all') }}"
  become: yes

  tasks:
    - include_tasks: tasks/apt.yml
    - include_tasks: tasks/restic.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/iptables.yml
    - include_tasks: tasks/crowdsec.yml

  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
