- hosts: "{{ target | default('all') }}"
  become: yes

  pre_tasks:
    - include_tasks: tasks/mc.yml
    - include_tasks: tasks/apt.yml
    - include_tasks: tasks/restic.yml
    - include_tasks: tasks/rclone.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/golang.yml
    - include_tasks: tasks/iptables.yml
    - include_tasks: tasks/crowdsec.yml
    - include_tasks: tasks/sysctl.yml

  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
