- name: Package installation
  apt: name={{ item }} update_cache=yes state=latest
  become: true
  with_items:
    - git
    - htop
    - neovim
    - ncdu
    - zip
    - unzip
    - locate
    - curl
    - tmux
    - jq
    - iputils-ping
    - trash-cli
    - ripgrep
    - fd-find
    - unattended-upgrades

- name: Configure unattended-upgrades
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
  become: true
