- name: Ensure Fail2ban is installed
  apt:
    name: fail2ban
    state: present

- name: Create Fail2ban jail.local configuration
  template:
    src: templates/jail.local
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Ensure Fail2ban service is enabled and started
  service:
    name: fail2ban
    enabled: yes
    state: started
